### PR TITLE
drop_intercept and more ...

### PR DESCRIPTION
**Pull request by bbolker**
in addition to the previously discussed drop_intercept, there a few other pieces here (sorry ...) in particular, I added an argument `model_name` to allow the default ("model") to be overridden

### CODE REVIEW

**Comment by fsolt** [comment]
Looks great, Ben, thanks!  One question, though: what's the use case for passing ... to tidy?  I know tidy takes them, but I haven't seen an example

**Comment by bbolker** [comment]
The mixed-model machinery that I was putting together for `broom` takes arguments specifying e.g. whether you want the fixed effects only, or the variance-covariance parameters (see `?tidy.merMod`).  So this would be something like

```
library(lme4)
library(dwplot)
gm1 <- glmer(cbind(incidence, size - incidence) ~ period + (1 | herd),
                    data = cbpp, family = binomial)  
dwplot(gm1,effects="fixed")
```

but actually I see that's broken somewhere:

```
Error: `breaks` and `labels` must have the same length
```

So let me see if I can fix that ...

**Comment by fsolt** [comment]
Okay, I can see that. I ask because I'd been hoping to use the dots arg to address #42.  Ah well, I'm not sure that would have worked anyway.

**Comment by bbolker** [comment]
wrap dot/whisker aesthetics in a list?

**Comment by fsolt** [comment]
I think we'll end up just pulling oft-used options and giving them each their own argument.  That's what @sammo3182 did for interplot (our other package).

**Pull request merged**
